### ISSUE TITLE
Basic Profiler Window

### ISSUE THREAD

**Issue by linusha** [hpi-swa-teaching/InteractiveProfilingTool#1]
Als Squeak-Entwickler*in möchte ich ein Fenster für den Profiler öffnen können um schnell darauf zuzugreifen.
* [x] Fenster kann geöffnet werden
* [x] Fenster enthält einen Button

**Comment by tillprochaska** [comment]
Schätzung: 3h

**Comment by linusha** [comment]
Einbindung in Tools-Menü ist in #25  verschoben.
