### ISSUE TITLE
Als Squeak-Entwickler*in möchte ich, Methodenaufrufe nach Methodennamen filtern können, damit ich mich beim Profiling auf eine bestimmte Methode konzentrieren kann.

### ISSUE THREAD

**Issue by linusha** [hpi-swa-teaching/InteractiveProfilingTool#13]

**Comment by linusha** [comment]
5h

**Comment by tillprochaska** [comment]
I think this needs some prior UX research?

* Should I be able to filter in the same way as I can in other list views, i. e. just type while your cursor is above the tree view?
* Or should there be a dedicated UI, e. g. with text inputs, select boxed, …
* Should nodes that do not match the filter be completely hidden? How would we handle cases where the parent node doesn’t match the filter, while child nodes do?
* Or nodes that match the filter be highlighted, e. g. using a different background color (or marking the part of the method name etc. that matches the filter)?

If we decide to go for a dedicated filter UI, we should also think about other filters that might be added in the near future, e. g. thresholds for runtime/memory usage etc.

![IMG_3852](https://user-images.githubusercontent.com/1512805/57738544-3fe7fa80-76b0-11e9-9b4a-a3803e89e3f1.jpg)

**Comment by twollnik** [comment]
> Should I be able to filter in the same way as I can in other list views, i. e. just type while your cursor is above the tree view?

This seems to be the Squeak-way to do it. We should find out what our customer thinks about this.

Estimate: 3 hours

**Comment by linusha** [comment]
UI research @nickpodratz

**Comment by Alexander-Dubrawski** [comment]
Wir wollen

* Methodennamen eingeben können
* Elemente des Baumes, die nicht darauf passen, werden ausgegraut.
* Gematcht werden sollen nicht nur 100%ige Übereinstimmungen, sondern auch teilweise.
