### ISSUE TITLE
Als Squeak-Entwickler*in möchte ich, dass Methodenaufrufe mit besonders hohem Speicherbedarf visuell hervorgehoben werden, damit ich Bottlenecks schneller sehe.

### ISSUE THREAD

**Issue by linusha** [hpi-swa-teaching/InteractiveProfilingTool#14]
## Spezifikation

* Alle Teilbäume mit Laufzeitanteil über Schwellenwert von 50% sollen hervorgehoben werden. Es gibt keine Abstufungen.
* Es sollen mehrerer Varianten getestet und mit Eva besprochen werden. Dafür Screenshots per Mail.

Mögliche Variationen:
* gesamten Text rot markieren
* nur relative Laufzeit rot markieren
* Icon anzeigen
* Text fetten

**Comment by tillprochaska** [comment]
Zusammenführen mit #19? Schätzung: 3h

**Comment by twollnik** [comment]
The feasability of this issue is questionable. We should talk with our customer about this.
