### ISSUE TITLE
Als Squeak-Entwickler*in möchte ich sehen wie viel Zeit mein Programm in welcher Methode verbringt um zu verstehen, wo mein Programm Laufzeitoptimierungspotential hat. Ich möchte absolute und relativ Werte sehen.

### ISSUE THREAD

**Issue by linusha** [hpi-swa-teaching/InteractiveProfilingTool#15]

**Comment by linusha** [comment]
@twollnik @tillprochaska @Alexander-Dubrawski @nickpodratz This seems to be in the current build that resulted from #16 right? Or am I missing something?

**Comment by tillprochaska** [comment]
I’m closing this as I think it’s a duplicated/is implemented in #29.
