### ISSUE TITLE
Akkumulierte Werte für mehrere (Teil-)Bäume

### ISSUE THREAD

**Issue by tillprochaska** [hpi-swa-teaching/InteractiveProfilingTool#20]
Als Squeak-Entwickler*in möchte ich im Profilingergebnis mehrere Einträge/(Teil-)Bäume auswählen können. Dann möchte ich die akkumulierten Werte (relative/absolute Laufzeit/Speicherbedarf etc.) für die ausgewählten Einträge sehen. Damit möchte ich gezielt bestimmte Teile des Programms analysieren und z. B. Submethodenaufrufe aus der Auswertung ausnehmen können.

**Comment by linusha** [comment]
Estimate: 3h?!

__I would find concrete acceptance criteria or a sketch helpful__

**Comment by tillprochaska** [comment]
I imagined something like in the sketch below, incorporating some kind of status bar. This is inspired by the macOS Finder. I’m unsure though how common this UX pattern is with other platforms, and there might be other ways to show this information.

We should probably try to come up with a few different UIs to solve that problem before doing any actual implementation work.

3h research/prototyping + 2-4 hours implementation (I’m unsure if the tree component allows for (multi-)selection).

![IMG_3851](https://user-images.githubusercontent.com/1512805/57737663-c39fe800-76ac-11e9-977a-efccaf2f6e4a.jpg)

![Screenshot 2019-05-15 01 00 44](https://user-images.githubusercontent.com/1512805/57737776-298c6f80-76ad-11e9-82be-e7504dcf3730.png)

**Comment by linusha** [comment]
@tillprochaska agreed on the prototyping part and the estimation.

The proposed UX pattern is extremely common in any explorer at least (win and linux). :+1:

**Comment by twollnik** [comment]
Thank you @tillprochaska for the sketch and the ideas. 

The `PluggableTreeSpec` allows users to specify methods for `getSelected`, `getSelectedPath` and `setSelectedPath` however I am unsure at the moment how excatly the given methods will be called and what their use is.

Estimate: 6 h

**Comment by tillprochaska** [comment]
> The PluggableTreeSpec allows users to specify methods for getSelected, getSelectedPath and setSelectedPath

Do you know if the tree component supports multi-select? I couldn’t find any info on this (and by default, this doesn’t seem to work.)

**Comment by twollnik** [comment]
I believe it does. Maybe `getSelected` can return a collection of nodes?

**Comment by linusha** [comment]
> I believe it does. Maybe `getSelected` can return a collection of nodes?

We could take a look at how the TestRunner imlements its selection since is supports multi-select?

**Comment by twollnik** [comment]
> We could take a look at how the TestRunner imlements its selection since is supports multi-select?

I like the idea of getting inspiration from other tools.

However the `TestRunner` may not be the best choice because it uses `PluggableListMorphOfMany` and not `PluggableTreeMorph`.

**Comment by linusha** [comment]
UI research @nickpodratz

**Comment by nickpodratz** [comment]
Eva said this feature is not essential. She is not sure either if it is easily possible, and doesn't see a use case in it either. We should put little priority to it or discard the user story entirely IMO.
