### ISSUE TITLE
Profiler über Tool-Menü öffnen  

### ISSUE THREAD

**Issue by linusha** [hpi-swa-teaching/InteractiveProfilingTool#25]
Als Squeak-Entwickler*in möchte ich den Profiler aus dem `WorldMenu` heraus starten können, damit er logisch bei allen anderen Tools zu finden ist.

* [x] Profiler-Button in WorldMenu -> Apps erstellen
* [x] Profiler bei Klick auf den Button starten

**Comment by linusha** [comment]
Habe den Button mit gewünscher Funktionalität erstellt. 
Es ist noch der GitBrowser davon zu überzeugen, dass diese Änderungen ebenfalls commitet werden können. Definitiv muss das Package hinzugefügt werden, vielleicht reicht das aber nicht, da ich die Änderungen bereits getätigt habe, bevor das Package getrackt wurde? Im Zweifel müssen wir da nochmal nachfragen.

**Comment by tillprochaska** [comment]
> Definitiv muss das Package hinzugefügt werden, vielleicht reicht das aber nicht, da ich die Änderungen bereits getätigt habe, bevor das Package getrackt wurde?

An welcher Stelle hast du die Änderungen denn vorgenommen? Musstest du dafür z. B. die Main Docking Bar anpassen?

**Comment by linusha** [comment]
> An welcher Stelle hast du die Änderungen denn vorgenommen? Musstest du dafür z. B. die Main Docking Bar anpassen?

Genau, ich habe die Klasse ```TheMainWorldDockingBar``` geändert. Das Package habe ich dann aber erst nach dem rumexperimentieren hinzugefügt, wodurch natürlich keine Änderungen getrackt werden können. Ich werde meine Änderungen einfach noch einmal zurücknehmen und dann getrackt neu einführen.

**Comment by twollnik** [comment]
Refer to `PowerSqueak>>registerInWorldMenu` for example registration.
Baseline has `postLoad` method.

**Comment by linusha** [comment]
Actual Timit until PR was issued: 2h. :heavy_check_mark:
