### ISSUE TITLE
auto expand all nodes

### ISSUE THREAD

**Issue by twollnik** [hpi-swa-teaching/InteractiveProfilingTool#30]
Als Squeak Entwickler*in möchte ich den Baum einfach expandieren, um mir einen schnellen Überblick verschaffen zu können.

**Comment by linusha** [comment]
Estimate: 2h

**Comment by tillprochaska** [comment]
I guess that means that there should be an option to expand all subtress with a single click?

Estimate: 2h

**Comment by linusha** [comment]
> I guess that means that there should be an option to expand all subtress with a single click?
Yes.

**Comment by twollnik** [comment]
Estmate: 2.5 h

**Comment by linusha** [comment]
UI research @nickpodratz

**Comment by nickpodratz** [comment]
Eva's response to this is that the expanded list should be the default presentation.
And that we eventually need to create our own tree to accomplish our ideas anyways... But let's see! :)
