### ISSUE TITLE
Keyboard shortcuts for tree navigation

### ISSUE THREAD

**Issue by tillprochaska** [hpi-swa-teaching/InteractiveProfilingTool#34]
As a developer, I’d like to be able to use keyboard shortcuts in order to navigate the nodes and collapse/expand subtrees because I hate having to use my mouse for every little interaction.

* Up/down arrow should select the next/previous node
* Left/right should collapse/expand a subtree
* Cmd + up/Cmd + down should collapse/expand all subtrees of the selected node

**Comment by tillprochaska** [comment]
Estimate: 4h

**Comment by linusha** [comment]
>     * Cmd + up/Cmd + down should collapse/expand all subtrees of the selected node

Is the only one missing, since the other features come with `APluggableTree`. 
This depends on #30.
