### ISSUE TITLE
refactoring

### ISSUE THREAD

**Issue by linusha** [hpi-swa-teaching/InteractiveProfilingTool#47]
* [x] Anpassung der Architektur entsprechend der Vortragsfolien
 * [x] Tests zum Wrapper hinzufügen
* [x] Einfügen des Wrappers an allen Stellen

Refactoring ist durch Architekturanpassungen relativ groß, viel Raum zum Fehlereinbauen. Ich halte das für nicht überdiemaßen komplex, sollte man aber denke ich daher nicht hetzen.

~~Die Stats Berechnung ercheint mir im InteractiveProfiler aus dem Image relativ transparent zu sein, die Berechnungen müssen lediglich an unsere Architektur angepasst werden.
Es sollte mit Eva besprochen werden, ob diese allgemeinen Stats einfach auch mit in den Baum kommen sollen, oder ob es dafür einen eigenen Bereich im Fenster geben soll.~~

**Comment by Alexander-Dubrawski** [comment]
@twollnik @nickpodratz 
Ich denke es ist beim Refactoring noch sinnvoll Code folgender Art in `IPTTreeModelTestCase >> setUp` einzufügen: 

```smalltalk

ClassBuilder new 
 		superclass: Object 
		subclass: #DummyClass 
		instanceVariableNames: '' 
		classVariableNames: '' 
		poolDictionaries: '' 
		category: 'InteractiveProfilingTool-Tests'.
		
DummyClass compile: self dummyMethodToProfileSourceCode.
	
DummyObject compile: self dummyMethodToRemoveSourceCode.
```

Damit erhöhen wir die Stabilität der Tests. Es kann passierten, dass zum Beispiel der Test `testSourceCodeWhenClassDoesNotExistAnymore` fehlschlägt. Ist dies der Fall muss die Klasse `DummyClass` welche in dem Test gelöscht wurde wieder manuell ins System eingefügt werden. Es ist also sinnvoll in der `setUp` Methode die Klasse zur Sicherheit einfach nochmal zu setzen. 
Übrigens ist es mittels dem Selektor `compile:` möglich in der Klasse eine Methode einzufügen. Mit dem `ClassBuilder` kannst du Klassen erstellen.
