### ISSUE TITLE
final beautifications

### ISSUE THREAD

**Issue by linusha** [hpi-swa-teaching/InteractiveProfilingTool#52]
# Readme

- [x] kein spy on (funktionalität des tools genau erklären)
- [x] relevance threshhold (erklären das es ihn gibt, welche auswirkung das hat, wo er geändert werden kann)
- [x] verweis auf gc doku
- [x] metacello instructions

# sonstiger Code

-  [x] userCallsRoot __(without s)__ nur für den Baum als Collection übergeben
- [ ] Negation in Bedingung @tillprochaska bitte spezifizieren oder zuständig sein :wink: 
- [x] genereller Konsistenzcheck
- [x] https://github.com/hpi-swa-teaching/InteractiveProfilingTool/pull/36
- [x] `checkIfSelectorIsTypeDoIt: aSelector inClass: aClass` in message tally wrapper
- [ ] Dummy Klassen für Tests in eigenes Package
- [x] >Sofern ich das richtig sehe, gibt es keinen Test, der den Fehler reproduziert, oder? Das wäre in meinen Augen noch das wichtigste.

# repo

- [x] project board aufräumen/löschen
- [x] issues aufräumen, einheitlich benennen
- [x] alte branches löschen

**Comment by linusha** [comment]
Readme @nickpodratz

**Comment by linusha** [comment]
userCalls Root & Konsistenzcheck @linusha @twollnik

**Comment by linusha** [comment]
Negation in Bedingung & checkIfSelectorIsTypeDoIt @tillprochaska

**Comment by linusha** [comment]
Dummy Klassen in eigenes Package @tillprochaska

**Comment by nickpodratz** [comment]
I updated the readme with the information from the list. I just don't know what gc docu refers to.
It would be great if someone could help me out on that. The branch I committed to was this one: https://github.com/hpi-swa-teaching/InteractiveProfilingTool/commits/readme. I'll open a PR in a second.

**Comment by linusha** [comment]
> I updated the readme with the information from the list. I just don't know what gc docu refers to.
> It would be great if someone could help me out on that. The branch I committed to was this one: https://github.com/hpi-swa-teaching/InteractiveProfilingTool/commits/readme. I'll open a PR in a second.

The readme should, in the optimal case, explain (on a basic level) explain how the Garbage-Collector in Squeak works, i.e. what the stats we show in the stats window refer to. There are some informations on this in our issues and at some point there were comments in the relevant code-sections. 
At the very least the readme should countain a link on where to find more information about the gc, so that people can look it up themselves. (Actually I think the link to documentation or something similar should be in the readme regardless of whether we explain it separately or not)
