### ISSUE TITLE
Als Squeak-Entwickler*in möchte ich zu jedem Methodenaufruf schnell den Quellcode sehen können, um zu verstehen, wie die Profilingergebnisse zustande kommen.

### ISSUE THREAD

**Issue by linusha** [hpi-swa-teaching/InteractiveProfilingTool#9]

**Comment by tillprochaska** [comment]
Schätzung: 4h

**Comment by twollnik** [comment]
The complexity of this user-story depends on how exactly we want to show the code. I guess that this issue goes beyond providing an easy way to access methods in the browser?
